-- Adds a short, human-readable sequential number to posts (e.g. "#123"),
-- for referencing posts in the UI and in conversation with Claude via MCP.
-- Separate from the uuid `id`, which stays the primary key everything else
-- (foreign keys, realtime, client-side optimistic inserts) keeps keying off.

-- "by default" (not "always") because a GENERATED ALWAYS identity column
-- can never be UPDATEd directly (Postgres error 428C9) — "by default" still
-- auto-generates the value whenever an insert doesn't supply one (which is
-- every insert this app makes; post_number is never in the app's insert
-- payloads), while still allowing the one-time backfill UPDATE below.
alter table posts add column post_number bigint generated by default as identity;

-- Identity columns don't backfill existing rows automatically — number the
-- existing seed posts in creation order so #1 is the oldest.
with numbered as (
  select id, row_number() over (order by created_at asc) as rn from posts
)
update posts set post_number = numbered.rn
from numbered
where posts.id = numbered.id;

-- Advance the identity sequence past the backfilled values so the next real
-- insert doesn't collide with them.
select setval(
  pg_get_serial_sequence('posts', 'post_number'),
  (select coalesce(max(post_number), 0) from posts)
);

alter table posts add constraint posts_post_number_unique unique (post_number);
create index posts_post_number_idx on posts (post_number);

-- Personal access tokens so a user can connect their own Claude (Desktop,
-- claude.ai custom connector, or Claude Code) to this app's MCP server and
-- have actions attributed to their own profile, same as the web UI.
create table api_tokens (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references profiles(id) on delete cascade,
  name text not null default 'Claude',
  token_hash text not null unique, -- sha-256 hex digest of the raw token; the raw token itself is never stored
  token_prefix text not null, -- first ~12 chars of the raw token, shown in the UI so a user can tell their tokens apart
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

alter table api_tokens enable row level security;

-- Same "wide open" posture as every other table for now (see schema.sql) —
-- tighten alongside the rest once real auth lands. In practice only the
-- owning user's own client reads/writes their own tokens, and only the
-- service-role client (MCP route) validates against this table.
create policy "open access" on api_tokens for all using (true) with check (true);
