import type { Category, Comment, Post, Profile } from "./types";

export const CURRENT_USER_ID = "profile-laura";

export const INITIAL_PROFILES: Profile[] = [
  { id: "profile-laura", fullName: "Laura Lisboa", email: "laura.lisboa@daredata.engineering", initials: "LL" },
  { id: "profile-mia", fullName: "Mia Pereira", email: "mia.pereira@daredata.engineering", initials: "MP" },
  { id: "profile-tomas", fullName: "Tomás Rocha", email: "tomas.rocha@daredata.engineering", initials: "TR" },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: "cat-meet-the-team", name: "Meet the Team" },
  { id: "cat-internal", name: "Internal" },
  { id: "cat-genos", name: "GenOS" },
];

const now = "2026-07-02T09:00:00.000Z";

export const INITIAL_POSTS: Post[] = [
  {
    id: "post-1",
    platform: "instagram",
    title: "GenOS offsite reel",
    description: "Behind-the-scenes reel from the GenOS offsite — the whole team in one room for the first time this year.",
    status: "backlog",
    targetDate: null,
    needsChanges: false,
    publishedUrl: null,
    assigneeId: "profile-mia",
    requestedById: "profile-laura",
    createdBy: "profile-laura",
    categoryIds: ["cat-internal"],
    images: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "post-2",
    platform: "x",
    title: "Pricing tiers teaser",
    description: "Quick take on the new pricing tiers we're rolling out next month.",
    status: "backlog",
    targetDate: null,
    needsChanges: false,
    publishedUrl: null,
    assigneeId: "profile-tomas",
    requestedById: null,
    createdBy: "profile-tomas",
    categoryIds: ["cat-genos"],
    images: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "post-3",
    platform: "linkedin",
    title: "Acme case study",
    description: "Case study draft: how Acme cut onboarding time by 40% using GenOS.",
    status: "writing",
    targetDate: "2026-07-09",
    needsChanges: false,
    publishedUrl: null,
    assigneeId: "profile-laura",
    requestedById: "profile-tomas",
    createdBy: "profile-tomas",
    categoryIds: ["cat-genos"],
    images: [
      { id: "img-post-3-1", postId: "post-3", imageUrl: "https://picsum.photos/seed/genos-case-study/800/600", position: 0 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "post-4",
    platform: "instagram",
    title: "New hires carousel",
    description: "Carousel introducing the new hires who joined us this quarter.",
    status: "designing",
    targetDate: "2026-07-11",
    needsChanges: true,
    publishedUrl: null,
    assigneeId: "profile-mia",
    requestedById: "profile-laura",
    createdBy: "profile-laura",
    categoryIds: ["cat-meet-the-team"],
    images: [
      { id: "img-post-4-1", postId: "post-4", imageUrl: "https://picsum.photos/seed/genos-new-hire-1/800/600", position: 0 },
      { id: "img-post-4-2", postId: "post-4", imageUrl: "https://picsum.photos/seed/genos-new-hire-2/800/600", position: 1 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "post-5",
    platform: "linkedin",
    title: "Q3 roadmap webinar",
    description: "Announcing the GenOS Q3 roadmap webinar — save the date and bring your questions.",
    status: "in_review",
    targetDate: "2026-07-14",
    needsChanges: false,
    publishedUrl: null,
    assigneeId: "profile-tomas",
    requestedById: null,
    createdBy: "profile-tomas",
    categoryIds: ["cat-genos"],
    images: [
      { id: "img-post-5-1", postId: "post-5", imageUrl: "https://picsum.photos/seed/genos-webinar-1/800/600", position: 0 },
      { id: "img-post-5-2", postId: "post-5", imageUrl: "https://picsum.photos/seed/genos-webinar-2/800/600", position: 1 },
      { id: "img-post-5-3", postId: "post-5", imageUrl: "https://picsum.photos/seed/genos-webinar-3/800/600", position: 2 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "post-6",
    platform: "x",
    title: "Outage postmortem thread",
    description: "Thread recapping last week's outage postmortem, in plain language.",
    status: "in_review",
    targetDate: "2026-07-12",
    needsChanges: true,
    publishedUrl: null,
    assigneeId: "profile-laura",
    requestedById: "profile-mia",
    createdBy: "profile-mia",
    categoryIds: ["cat-internal"],
    images: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "post-7",
    platform: "linkedin",
    title: "Hiring: data engineer",
    description: "We're hiring: looking for a senior data engineer to join the platform team.",
    status: "approved",
    targetDate: "2026-07-15",
    needsChanges: false,
    publishedUrl: null,
    assigneeId: "profile-mia",
    requestedById: "profile-laura",
    createdBy: "profile-laura",
    categoryIds: ["cat-internal"],
    images: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "post-8",
    platform: "instagram",
    title: "Dark mode teaser",
    description: "Product teaser: dark mode is finally here.",
    status: "scheduled",
    targetDate: "2026-07-16",
    needsChanges: false,
    publishedUrl: null,
    assigneeId: "profile-tomas",
    requestedById: null,
    createdBy: "profile-tomas",
    categoryIds: ["cat-genos"],
    images: [
      { id: "img-post-8-1", postId: "post-8", imageUrl: "https://picsum.photos/seed/genos-dark-mode/800/600", position: 0 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "post-9",
    platform: "x",
    title: "GenOS 2.4 release thread",
    description: "GenOS 2.4 is live — release notes thread.",
    status: "published",
    targetDate: "2026-07-02",
    needsChanges: false,
    publishedUrl: "https://x.com/genos/status/example",
    assigneeId: "profile-laura",
    requestedById: null,
    createdBy: "profile-laura",
    categoryIds: ["cat-genos"],
    images: [
      { id: "img-post-9-1", postId: "post-9", imageUrl: "https://picsum.photos/seed/genos-release-1/800/600", position: 0 },
      { id: "img-post-9-2", postId: "post-9", imageUrl: "https://picsum.photos/seed/genos-release-2/800/600", position: 1 },
    ],
    createdAt: now,
    updatedAt: now,
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: "comment-1",
    postId: "post-4",
    authorId: "profile-laura",
    body: "Can we swap the last slide for a group photo instead of headshots?",
    createdAt: "2026-06-28T10:15:00.000Z",
  },
  {
    id: "comment-2",
    postId: "post-6",
    authorId: "profile-mia",
    body: "Legal wants to review the wording around the outage cause before this goes out.",
    createdAt: "2026-06-29T14:40:00.000Z",
  },
  {
    id: "comment-3",
    postId: null,
    authorId: "profile-tomas",
    body: "Reminder: no posts going out the week of the 20th, I'm out on leave.",
    createdAt: "2026-06-30T08:00:00.000Z",
  },
];
